name: 'Hello World'
description: 'Greet someone'
inputs:
  name:
    description: 'Your name'
    default: 'No name provided'
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.name }}.
      shell: bash
    - run: echo "Nice to meet you!"
      shell: pwsh
    - run: echo "Recurse!"
      shell: bash
    - name: Run Cypress With Retries on Failures
      shell: bash
      uses: nick-invision/retry@7c68161adf97a48beb850a595b8784ec57a98cbb  # v2.4.0, but using commit hash for security.
      with:
        command: ls -al