name: deploy

on:
  push:
    branches:
      - develop
    paths:
      - requirements.txt
      - setup.py
      - Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: sleep 300
