name: deploy

on:
  push:
    branches:
      - develop
    paths:
      - requirements.txt
      - setup.py
      - Dockerfile
      - docker/Dockerfile
      - docker/entrypoint.sh

jobs:
  deploy-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: sleep 300
